---
abstract: 'Create a single .t for each compilable file in a distribution'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Dist::Zilla::Util::Test::KENTNL: '1.003002'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::DZil: '0'
  Test::File::ShareDir::Dist: '0'
  Test::More: '0.89'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Test-Compile-PerFile
provides:
  Dist::Zilla::Plugin::Test::Compile::PerFile:
    file: lib/Dist/Zilla/Plugin/Test/Compile/PerFile.pm
    version: '0.003001'
recommends:
  Moose: '2.000'
  Path::Tiny: '0.058'
requires:
  Dist::Zilla::File::FromCode: '0'
  Dist::Zilla::Plugin::FinderCode: '0'
  Dist::Zilla::Role::FileGatherer: '0'
  Dist::Zilla::Role::TextTemplate: '0'
  File::ShareDir: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::LazyRequire: '0'
  Path::Tiny: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Test-Compile-PerFile/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Test-Compile-PerFile
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Test-Compile-PerFile.git
version: '0.003001'
